
volumes:
  pg-data: 

services:
  
  postgres:
    # container_name: postgres
    image: postgres:18-alpine
    volumes:
      - pg-data:/var/lib/postgresql/18/docker
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - nginx-proxy-manager_default

  app:
    # container_name: app
    build: .
    env_file:
      - stack.env
    depends_on:
      - postgres
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true